//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComuniGamesWeb.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Endereco
    {
        public Endereco()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int ID { get; set; }
        public int CidadeID { get; set; }
        public string Logradouro { get; set; }
        public int Numero { get; set; }
        public string Complemento { get; set; }
        public string CEP { get; set; }
        public bool MostraLocalizacao { get; set; }
    
        public virtual Cidade Cidade { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
