//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComuniGamesWeb.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int UserId { get; set; }
        public int EnderecoId { get; set; }
        public string Nome { get; set; }
        public string Sobrenome { get; set; }
        public string CPF { get; set; }
        public string Senha { get; set; }
        public string Avatar { get; set; }
        public System.DateTime Nascimento { get; set; }
        public string DDDTelefone { get; set; }
        public string Telefone { get; set; }
        public string DDDCelular { get; set; }
        public string Celular { get; set; }
        public string Skype { get; set; }
        public bool Sexo { get; set; }
        public string PSN { get; set; }
        public string XboxLive { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public Nullable<System.DateTime> DataModificacao { get; set; }
        public bool Ativo { get; set; }
        public bool NotificacaoWishList { get; set; }
    
        public virtual Endereco Endereco { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
